### ISSUE TITLE
hello, pytest error is coming

### ISSUE THREAD

**Issue by sunithak** [Friz-zy/test_blue_yonder#1]
'pandoc' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "C:\Users\Sunitha\git\test_blue_yonder\setup.py", line 39, in <module>
    long_description=md2rst(join(dirname(__file__), 'README.md')),
  File "C:\Users\Sunitha\git\test_blue_yonder\setup.py", line 26, in md2rst
    with open(rst) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Sunitha\\git\\test_blue_yonder\\README.rst'

**Comment by Friz-zy** [comment]
Hi, setup.py requires external `pandoc` program for converting markdown into rest because PYPI understand only rest for long description.
Also I didn't tested it on windows because I'm linux guy

**Comment by sunithak** [comment]
i solved it
